import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-full h-4000">
          <div className="w-full h-110 flex flex-row">
          <input type="text" className="w-450 h-38 border-2"/>
          <button className="w-68 h-38 outline-black bg-gray-300">
            <Link href='/recipe'>recipe</Link>
          </button>
          
          </div>
          {children}
        </div>
        
      </body>
    </html>
  );
}
